### PR TITLE
appveyor.yml CI config

### PR DESCRIPTION
**Pull request by chcg**
- initial appveyor.yml CI config
- used https://github.com/autofac/Autofac/blob/develop/Autofac.snk to provide the needed Key.snk for signing, see https://groups.google.com/forum/#!topic/automatak-dnp3/DzC4Cs_496s

, see https://ci.appveyor.com/project/chcg/snip2codenet/build/1.0.0.6

### CODE REVIEW

**Comment by chcg** [comment]
@cghersi Any plans to update this project and prepare for x64?

**Comment by chcg** [comment]
@cghersi Any plans to update this project and prepare for x64?

**Comment by chcg** [comment]
@cghersi Any plans to update this project and prepare for x64?

**Comment by cghersi** [comment]
@chcg : is this PR meant to port the solution to an x64 platform?

**Comment by chcg** [comment]
@cghersi As preparation, to have a reproducible CI build as countercheck. I could also add a PR for x64 adaptations or extend this one.
Similar to e.g. https://github.com/cpmcgrath/codealignment/pull/59

**Comment by cghersi** [comment]
@chcg please go ahead with x64 adaptations on this PR, once complete we will merge it in the master

**Comment by chcg** [comment]
@cghersi Hi, I think the stuff for x64 is added now. 
- See https://ci.appveyor.com/project/chcg/snip2codenet/build/1.0.0.12.
- Just the frontend dll with the n++ win32 connection needs to be x86/x64 the remaining dlls could be AnyCPU.
- updated the contained nuget packages
- currently just Snip2Code.dll is publish at appveyor, this could be extended
- maybe fastJson could also be taken from nuget at https://www.nuget.org/packages/fastJSON/
- probably it is also possible to place the additional dlls into a subfolder below the n++ plugins dir instead of parallel to n++ or use ilmerge to create just one single binary as done in https://github.com/megaboich/js-map-parser/blob/master/source/JsParser.NppPlugin/JsParser.NppPlugin.csproj

**Pull request merged**
